Args = \
  -H:+UseServiceLoaderFeature \
  --initialize-at-build-time=com.qxotic.jota.DataTypeImpl \
  --initialize-at-build-time=com.qxotic.jota.runtime \
  --initialize-at-build-time=com.qxotic.jota.runtime.spi
