package com.qxotic.jota.tensor;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;

import com.qxotic.jota.DataType;
import com.qxotic.jota.Shape;
import com.qxotic.jota.random.RandomKey;
import com.qxotic.jota.testutil.RunOnAllAvailableBackends;
import com.qxotic.jota.testutil.TensorTestReads;
import org.junit.jupiter.api.Test;

@RunOnAllAvailableBackends
class RandomGoldenVectorTest {

    // Generated by tools/generate_rng_golden.py (seed=1234, count=64).
    private static final int[] EXPECTED_FP32_BITS = {
        0x3f5b911d, 0x3f74f72a, 0x3d65d370, 0x3e1f0d10, 0x3e8252a2, 0x3eb51ebc, 0x3ee7ead6,
        0x3f0d5b78, 0x3f26c185, 0x3f402792, 0x3f598d9f, 0x3f72f3ac, 0x3d459b90, 0x3e16ff18,
        0x3e7c974c, 0x3eb117c0, 0x3ee3e3da, 0x3f0b57fa, 0x3f24be07, 0x3f3e2414, 0x3f578a21,
        0x3f70f02e, 0x3d2563b0, 0x3e0ef120, 0x3e748954, 0x3ead10c4, 0x3edfdcde, 0x3f09547c,
        0x3f22ba89, 0x3f3c2096, 0x3f5586a3, 0x3f6eecb0, 0x3d052bd0, 0x3e06e328, 0x3e6c7b5c,
        0x3ea909c8, 0x3edbd5e2, 0x3f0750fe, 0x3f20b70b, 0x3f3a1d18, 0x3f538325, 0x3f6ce932,
        0x3cc9e7e0, 0x3dfdaa60, 0x3e646d64, 0x3ea502cc, 0x3ed7cee6, 0x3f054d80, 0x3f1eb38d,
        0x3f38199a, 0x3f517fa7, 0x3f6ae5b4, 0x3c897820, 0x3ded8e70, 0x3e5c5f6c, 0x3ea0fbd0,
        0x3ed3c7ea, 0x3f034a02, 0x3f1cb00f, 0x3f36161c, 0x3f4f7c29, 0x3f68e236, 0x3c1210c0,
        0x3ddd7280,
    };

    // Generated by tools/generate_rng_golden.py (seed=2026, count=32).
    private static final int[] EXPECTED_FP32_BITS_SEED_2026 = {
        0x3f58aa27, 0x3f721034, 0x3d376410, 0x3e137138, 0x3e79096c, 0x3eaf50d0, 0x3ee21cea,
        0x3f0a7482, 0x3f23da8f, 0x3f3d409c, 0x3f56a6a9, 0x3f700cb6, 0x3d172c30, 0x3e0b6340,
        0x3e70fb74, 0x3eab49d4, 0x3ede15ee, 0x3f087104, 0x3f21d711, 0x3f3b3d1e, 0x3f54a32b,
        0x3f6e0938, 0x3cede8a0, 0x3e035548, 0x3e68ed7c, 0x3ea742d8, 0x3eda0ef2, 0x3f066d86,
        0x3f1fd393, 0x3f3939a0, 0x3f529fad, 0x3f6c05ba,
    };

    // Generated by tools/generate_rng_golden.py (seed=1234, count=64).
    private static final long[] EXPECTED_FP64_BITS = {
        0x3fcb7223bcef7f60L, 0x3fce9ee559d0f204L, 0x3fd0e5d37b593254L, 0x3fd27c3449c9eba6L,
        0x3fd41295183aa4f8L, 0x3fd5a8f5e6ab5e4aL, 0x3fd73f56b51c179cL, 0x3fd8d5b7838cd0eeL,
        0x3fda6c1851fd8a40L, 0x3fdc0279206e4392L, 0x3fdd98d9fedefce4L, 0x3fdf2f3acd4fb636L,
        0x3fe062cdcde037c4L, 0x3fe12dfe3518946dL, 0x3fe1f92e9c50f116L, 0x3fe2c45f03894dbfL,
        0x3fe38f8f6ac1aa68L, 0x3fe45abfd1fa0711L, 0x3fe525f0393263baL, 0x3fe5f120a06ac063L,
        0x3fe6bc510fa31d0cL, 0x3fe7878176db79b5L, 0x3fe852b1de13d65eL, 0x3fe91de2454c3307L,
        0x3fe9e912ac848fb0L, 0x3feab44313bcec59L, 0x3feb7f737af54902L, 0x3fec4aa3e22da5abL,
        0x3fed15d449660254L, 0x3fede104b09e5efdL, 0x3feeac351fd6bba6L, 0x3fef7765870f184fL,
        0x3f80a57b91dd3e00L, 0x3fa0dc6557fd1a10L, 0x3fad8f6bcb82e4a0L, 0x3fb521391f845798L,
        0x3fbb7abc59473ce0L, 0x3fc0ea1fc9851114L, 0x3fc416e1666683b8L, 0x3fc743a30347f65cL,
        0x3fca7064a0296900L, 0x3fcd9d265d0adba4L, 0x3fd064f3fcf62724L, 0x3fd1fb54cb66e076L,
        0x3fd391b599d799c8L, 0x3fd528166848531aL, 0x3fd6be7736b90c6cL, 0x3fd854d80529c5beL,
        0x3fd9eb38d39a7f10L, 0x3fdb8199a20b3862L, 0x3fdd17fa707bf1b4L, 0x3fdeae5b4eecab06L,
        0x3fe0225e0eaeb22cL, 0x3fe0ed8e75e70ed5L, 0x3fe1b8bedd1f6b7eL, 0x3fe283ef4457c827L,
        0x3fe34f1fab9024d0L, 0x3fe41a5012c88179L, 0x3fe4e5807a00de22L, 0x3fe5b0b0e1393acbL,
        0x3fe67be148719774L, 0x3fe74711b7a9f41dL, 0x3fe812421ee250c6L, 0x3fe8dd72861aad6fL,
    };

    // Generated by tools/generate_rng_golden.py (seed=2026, count=32).
    private static final long[] EXPECTED_FP64_BITS_SEED_2026 = {
        0x3fdd8aa27c1442b4L, 0x3fdf21034a84fc06L, 0x3fe05bb20c7adaacL, 0x3fe126e273b33755L,
        0x3fe1f212daeb93feL, 0x3fe2bd434223f0a7L, 0x3fe38873a95c4d50L, 0x3fe453a41094a9f9L,
        0x3fe51ed47fcd06a2L, 0x3fe5ea04e705634bL, 0x3fe6b5354e3dbff4L, 0x3fe78065b5761c9dL,
        0x3fe84b961cae7946L, 0x3fe916c683e6d5efL, 0x3fe9e1f6eb1f3298L, 0x3feaad2752578f41L,
        0x3feb7857b98febeaL, 0x3fec438820c84893L, 0x3fed0eb88800a53cL, 0x3fedd9e8f73901e5L,
        0x3feea5195e715e8eL, 0x3fef7049c5a9bb37L, 0x3f7dbd16710bf000L, 0x3fa06aa941a74890L,
        0x3fad1dafb52d1320L, 0x3fb4e85b14596ed8L, 0x3fbb41de4e1c5420L, 0x3fc0cdb0c3ef9cb4L,
        0x3fc3fa7260d10f58L, 0x3fc727341db281fcL, 0x3fca53f5ba93f4a0L, 0x3fcd80b757756744L,
    };

    @Test
    void randFp32MatchesPythonGoldenBits() {
        Tensor t =
                Tensor.rand(
                        Shape.of(EXPECTED_FP32_BITS.length), DataType.FP32, RandomKey.of(1234L));
        assertArrayEquals(EXPECTED_FP32_BITS, toFp32Bits(t));
    }

    @Test
    void randFp64MatchesPythonGoldenBits() {
        Tensor t =
                Tensor.rand(
                        Shape.of(EXPECTED_FP64_BITS.length), DataType.FP64, RandomKey.of(1234L));
        assertArrayEquals(EXPECTED_FP64_BITS, toFp64Bits(t));
    }

    @Test
    void tracedRandFp32MatchesPythonGoldenBits() {
        Tensor t =
                Tracer.trace(
                        Tensor.rand(
                                Shape.of(EXPECTED_FP32_BITS.length),
                                DataType.FP32,
                                RandomKey.of(1234L)),
                        x -> x);
        assertArrayEquals(EXPECTED_FP32_BITS, toFp32Bits(t));
    }

    @Test
    void tracedRandFp64MatchesPythonGoldenBits() {
        Tensor t =
                Tracer.trace(
                        Tensor.rand(
                                Shape.of(EXPECTED_FP64_BITS.length),
                                DataType.FP64,
                                RandomKey.of(1234L)),
                        x -> x);
        assertArrayEquals(EXPECTED_FP64_BITS, toFp64Bits(t));
    }

    @Test
    void randForSecondSeedMatchesPythonGoldenBits() {
        Tensor t32 =
                Tensor.rand(
                        Shape.of(EXPECTED_FP32_BITS_SEED_2026.length),
                        DataType.FP32,
                        RandomKey.of(2026L));
        Tensor t64 =
                Tensor.rand(
                        Shape.of(EXPECTED_FP64_BITS_SEED_2026.length),
                        DataType.FP64,
                        RandomKey.of(2026L));
        assertArrayEquals(EXPECTED_FP32_BITS_SEED_2026, toFp32Bits(t32));
        assertArrayEquals(EXPECTED_FP64_BITS_SEED_2026, toFp64Bits(t64));
    }

    @Test
    void tracedRandForSecondSeedMatchesPythonGoldenBits() {
        Tensor t32 =
                Tracer.trace(
                        Tensor.rand(
                                Shape.of(EXPECTED_FP32_BITS_SEED_2026.length),
                                DataType.FP32,
                                RandomKey.of(2026L)),
                        x -> x);
        Tensor t64 =
                Tracer.trace(
                        Tensor.rand(
                                Shape.of(EXPECTED_FP64_BITS_SEED_2026.length),
                                DataType.FP64,
                                RandomKey.of(2026L)),
                        x -> x);
        assertArrayEquals(EXPECTED_FP32_BITS_SEED_2026, toFp32Bits(t32));
        assertArrayEquals(EXPECTED_FP64_BITS_SEED_2026, toFp64Bits(t64));
    }

    private static int[] toFp32Bits(Tensor tensor) {
        int[] out = new int[Math.toIntExact(tensor.shape().size())];
        for (int i = 0; i < out.length; i++) {
            float value = TensorTestReads.readFloat(tensor, i);
            out[i] = Float.floatToRawIntBits(value);
        }
        return out;
    }

    private static long[] toFp64Bits(Tensor tensor) {
        long[] out = new long[Math.toIntExact(tensor.shape().size())];
        for (int i = 0; i < out.length; i++) {
            double value =
                    ((Number) TensorTestReads.readValue(tensor, i, DataType.FP64)).doubleValue();
            out[i] = Double.doubleToRawLongBits(value);
        }
        return out;
    }
}
