package com.qxotic.toknroll.testkit;

import java.util.List;

/** Centralized test string corpora for tokenizer and splitter tests. */
public final class TestCorpora {

    private TestCorpora() {}

    public static final List<String> SPLITTER_CONTRACT_SAMPLES =
            List.of(
                    "",
                    "plain ascii words",
                    "digits 0 1 12 123 1234 12345 123456",
                    "long digits 123456789012345678901234567890",
                    "numeric mix v1beta2 build42 x86_64 arm64",
                    "unicode digits ١٢٣ ۱۲۳ १२३ １２３",
                    "numbers with punctuation 3.14159 -42 +7e10 1,000,000",
                    "ids and versions user_001 order-2026-04-03 api/v2.5.1",
                    "a\u0000b\u0001c\u001Fd",
                    "line1\rline2\r\nline3\nline4",
                    "tabs\t\tspaces  end",
                    "leading separators ,,,hello",
                    "trailing separators world!!!",
                    "adjacent separators !!!???...,,;;::",
                    "boundary punctuation (start) [token] (end)",
                    "quotes and apostrophes '' ''' don't I'M WE'RE THEY'LL",
                    "emoji 👨‍👩‍👧‍👦 and flags 🇺🇳🇯🇵",
                    "ZWJ family 👨‍👩‍👧‍👦 + kiss 👩‍❤️‍💋‍👨",
                    "skin tones 👍🏻👍🏽👍🏿",
                    "flags 🇺🇳 🇺🇸 🇯🇵",
                    "keycaps 1️⃣ 2️⃣ #️⃣ *️⃣",
                    "variation selectors ✊︎ ✊️",
                    "combining e\u0301 vs é, n\u0303 vs ñ",
                    "lone surrogates \uD800 \uDC00 end",
                    "bidi marks A\u200EB\u200FC \u202Astart\u202C",
                    "rtl عربي עברית فارسی",
                    "rtl mix العربية English עברית 123",
                    "arabic detailed: مرحبًا بالعالم، كيف الحال؟ الإصدار ٢٫٥ جاهز.",
                    "hebrew detailed: שלום עולם, מה שלומך? גרסה 2.5 מוכנה.",
                    "persian detailed: سلام دنیا، حالت چطوره؟ نسخه ۲٫۵ آماده است.",
                    "urdu detailed: ہیلو دنیا، آپ کیسے ہیں؟ ورژن ۲٫۵ تیار ہے۔",
                    "pashto detailed: سلام نړۍ، ته څنګه یې؟ نسخه ۲٫۵ چمتو ده.",
                    "rtl punctuation mix: العربية؛ עברית، فارسی؟ yes/no.",
                    "cjk 你好 日本語 한글",
                    "chinese simplified: 今天天气很好，我们一起去公园散步，然后喝茶。",
                    "chinese traditional: 今天天氣很好，我們一起去公園散步，然後喝茶。",
                    "japanese mixed: 今日は良い天気です。カタカナとひらがな、そして漢字。",
                    "japanese numbers: 第3版は2026年4月3日に公開されました。",
                    "thai ไทยภาษาไทย without spaces",
                    "thai detailed: สวัสดีชาวโลก วันนี้อากาศดีมาก ไปเดินเล่นกันไหม",
                    "thai with digits: เวอร์ชัน 2.5 เปิดตัววันที่ 03/04/2026",
                    "indic नमस्ते दुनिया தமிழ் ಕನ್ನಡ বাংলা",
                    "vietnamese: Xin chào thế giới, hôm nay trời đẹp quá!",
                    "turkish: Merhaba dünya, nasılsın? Sürüm 2.5 hazır.",
                    "russian: Привет, мир! Версия 2.5 уже доступна.",
                    "greek: Γειά σου κόσμε, η έκδοση 2.5 είναι έτοιμη.",
                    "controls a\u200Db\u200Cc\uFE0Fd",
                    "hangul 한글 테스트",
                    "math ∑∏√∞ ≠ ≤ ≥",
                    "private use \uE000\uE001",
                    "noncharacters \uFDD0 \uFDEF",
                    "punctuation []{}()!?.,;:/\\\"'",
                    "long punctuation !!!???...,,;;::--__",
                    "spaces  \t\n\r\n  end");

    public static final List<String> SPLITTER_PARITY_SAMPLES =
            List.of(
                    "Hello world",
                    "Hello, world!!!",
                    "It's we're THEY'LL I'd",
                    "  leading and trailing  ",
                    "tabs\tand\nnewlines\r\n",
                    "numbers 7 42 123 456789",
                    "digit lengths: 0 1 12 123 1234 12345 123456 1234567",
                    "long numeric run: 1234567890123456789012345678901234567890",
                    "unicode digits: ١٢٣ ۱۲۳ १२३ １２３",
                    "versions: v1 v2.5 v10.12.003 build-20260403",
                    "scientific-ish: +7 -42 3.14159 6.022e23 -1.6E-19",
                    "dates and times: 2026-04-03 23:59:59 03/04/2026",
                    "mixed alnum: a1 b22 c333 d4444 z99x",
                    "symbols <>[]{}()/*+-=_",
                    "separators at boundaries: ,start middle,end!",
                    "dense separators: !!!???...,,;;::--__",
                    "slashes and dots: path/to/v1.2.3/file.ext",
                    "mix: 'S 'T 'Re 'vE 'M 'Ll 'D",
                    "apostrophes: don't I'm we're THEY'LL I'd",
                    "emoji 😀 fallback",
                    "emoji sequence: 👨‍👩‍👧‍👦",
                    "emoji sequence: 👩‍👩‍👧‍👦",
                    "emoji sequence: 👨‍👨‍👧‍👧",
                    "skin tone: 👍🏽",
                    "modifier base + tone: 👩🏾 👨🏻 🧑🏿",
                    "emoji ZWJ: 🧑‍💻 👨‍🔬 👩‍🚀",
                    "emoji ZWJ flags: 🏳️‍🌈 🏳️‍⚧️ 🏴‍☠️",
                    "variation selectors: ☺︎ ☺️ ✈︎ ✈️",
                    "keycaps: 1️⃣ #️⃣ *️⃣",
                    "regional indicators odd/even: 🇺🇸🇨🇦🇲",
                    "flags: 🇺🇳 🇯🇵",
                    "combining: e\u0301 n\u0303 a\u0308",
                    "combining without base: \u0301\u0308\u0304",
                    "Accents: café mañana résumé",
                    "normalization pairs: é e\u0301 Å A\u030A Å",
                    "Cyrillic: Привет мир",
                    "Greek: Γειά σου κόσμε",
                    "Arabic: مرحبا بالعالم",
                    "Hebrew: שלום עולם",
                    "Arabic detailed: مرحبًا بالعالم، كيف الحال؟ الإصدار ٢٫٥ جاهز.",
                    "Hebrew detailed: שלום עולם, מה שלומך? גרסה 2.5 מוכנה.",
                    "Persian (RTL): سلام دنیا، حال شما چطور است؟",
                    "Urdu (RTL): ہیلو دنیا، آپ کیسے ہیں؟",
                    "Pashto (RTL): سلام نړۍ، ته څنګه یې؟",
                    "RTL punctuation mix: العربية؛ עברית، فارسی؟ yes/no.",
                    "Arabic + Latin mix: الإصدار v2.5 متاح الآن!",
                    "Hebrew + numbers: גרסה 2.5 זמינה עכשיו",
                    "RTL punctuation: مرحبًا، كيف الحال؟ نعم؛ بالتأكيد!",
                    "Hindi (Devanagari): नमस्ते दुनिया, आप कैसे हैं?",
                    "Marathi (Devanagari): नमस्कार जग, तुम्ही कसे आहात?",
                    "Bengali: নমস্কার বিশ্ব, আপনি কেমন আছেন?",
                    "Gujarati: નમસ્તે વિશ્વ, તમે કેમ છો?",
                    "Punjabi (Gurmukhi): ਸਤ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ, ਤੁਸੀਂ ਕਿਵੇਂ ਹੋ?",
                    "Odia: ନମସ୍କାର ବିଶ୍ୱ, ଆପଣ କେମିତି ଅଛନ୍ତି?",
                    "Tamil: வணக்கம் உலகம், நீங்கள் எப்படி இருக்கிறீர்கள்?",
                    "Telugu: నమస్కారం ప్రపంచం, మీరు ఎలా ఉన్నారు?",
                    "Kannada: ನಮಸ್ಕಾರ ವಿಶ್ವ, ನೀವು ಹೇಗಿದ್ದೀರಾ?",
                    "Malayalam: നമസ്കാരം ലോകമേ, നിങ്ങൾ സുഖമാണോ?",
                    "CJK: 你好 世界 日本語",
                    "Chinese (Simplified): 今天天气很好，我们去公园散步。",
                    "Chinese (Traditional): 今天天氣很好，我們去公園散步。",
                    "Japanese: 今日はいい天気ですね。カタカナとひらがな。",
                    "Japanese mixed: 今日は良い天気です。カタカナとひらがな、そして漢字。",
                    "Japanese numbers: 第3版は2026年4月3日に公開されました。",
                    "Korean: 안녕하세요 세계, 오늘 날씨가 좋네요.",
                    "Thai: สวัสดีชาวโลก",
                    "Thai detailed: สวัสดีชาวโลก วันนี้อากาศดีมาก ไปเดินเล่นกันไหม",
                    "Thai with digits: เวอร์ชัน 2.5 เปิดตัววันที่ 03/04/2026",
                    "Vietnamese: Xin chào thế giới, hôm nay trời đẹp quá.",
                    "Turkish: Merhaba dünya, nasılsın?",
                    "German: Grüße, Fußballstraße und Überraschung!",
                    "Spanish: ¡Hola mundo! ¿Cómo estás?",
                    "French: Salut le monde, où êtes-vous?",
                    "Indic conjuncts: क्ष क्\u200Dष क्\u200Cष",
                    "Hangul jamo: 한 vs precomposed: 한",
                    "NBSP:\u00A0x\u00A0y",
                    "line separators:\u2028x\u2029y",
                    "zero-width controls: a\u200Bb\u200Cc\u200Dd\uFEFFe",
                    "bidi controls: a\u200Fb\u202Ec\u202Cd",
                    "isolated CR and LF: a\rb\nc",
                    "lone surrogates: \uD83D x \uDC00 y",
                    "math: 1+2=3; 4*5/6",
                    "hex and binary: 0xFF 0b101010 0755",
                    "json: {\"a\":1,\"b\":[true,false,null]}",
                    "code: for(i=0;i<10;i++){sum+=i;} // done",
                    "slashes and CRLF: a/b\\c\r\nnext");

    public static final List<String> QWEN35_SPLITTER_REPRESENTATIVE_SAMPLES =
            List.of(
                    "Hello world",
                    "It's we're THEY'LL I'd",
                    "digits 1234567890",
                    "versions v2.5.1 build-20260403",
                    "unicode digits ١٢٣ ۱۲۳ १२३ １２３",
                    "  leading and trailing  ",
                    "tabs\tand\nnewlines\r\n",
                    "symbols <>[]{}()/*+-=_",
                    "emoji 😀 fallback",
                    "Accents: café mañana résumé",
                    "Hindi: नमस्ते दुनिया",
                    "Arabic: مرحبا بالعالم");

    public static final List<String> REGEX_SPLITTER_CORNER_SAMPLES =
            List.of(
                    "",
                    "12345678901234567890",
                    "0 1 12 123 1234 12345 123456",
                    "١٢٣ ۱۲۳ १२३ １２３",
                    "v1.2.3 build-2026-04-03",
                    "...leading and trailing!!!",
                    "adjacent !!!???...,,;;::",
                    "path/to/api/v2.5.1?x=1&y=22",
                    "don't I'M WE'RE THEY'LL I'd",
                    "tabs\t\n and spaces  ",
                    "emoji 😀 123 and symbols #!@");

    public static final List<String> MODEL_TOKENIZER_AGREEMENT_TEXTS =
            List.of(
                    "Tokenization agreement test baseline.",
                    "Numbers 0 1 12 123 1234 and 3.14159 plus -42.",
                    "Code: for(i=0;i<10;i++){sum+=i;} // done",
                    "JSON: {\"id\":123,\"ok\":true,\"tags\":[\"a\",\"b\"]}",
                    "Emoji 😀 👨‍👩‍👧‍👦 and flags 🇺🇳🇯🇵.",
                    "Arabic مرحبًا بالعالم، كيف الحال؟",
                    "Hebrew שלום עולם, מה שלומך?",
                    "Japanese 今日は良い天気です。カタカナとひらがな、そして漢字。",
                    "Thai สวัสดีชาวโลก วันนี้อากาศดีมาก",
                    "Mixed RTL/LTR العربية English עברית 123",
                    "Spacing  with   multiple\tseparators\nacross lines");
}
