package com.qxotic.toknroll.corpus;

import com.qxotic.format.json.Json;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Represents ground truth tokenization data for a corpus.
 *
 * <p>Loaded from JSON files generated by the Python ground truth generator. Each entry contains the
 * expected tokens, decoded text, and token count for a specific chunk.
 */
public final class GroundTruthData {

    private final String sourceName; // e.g., "tiktoken_cl100k_base" or "hf_meta_llama3"
    private final List<Entry> entries;

    private GroundTruthData(String sourceName, List<Entry> entries) {
        this.sourceName = Objects.requireNonNull(sourceName);
        this.entries = List.copyOf(entries);
    }

    public String sourceName() {
        return sourceName;
    }

    public List<Entry> entries() {
        return entries;
    }

    public int size() {
        return entries.size();
    }

    /**
     * Load ground truth from a JSON resource or file.
     *
     * @param name The name of the ground truth source (for reporting)
     * @param jsonPath Path to the JSON file (absolute) or resource path (relative to classpath)
     * @return The loaded ground truth data
     */
    @SuppressWarnings("unchecked")
    public static GroundTruthData load(String name, String jsonPath) {
        String json;
        Path path = Paths.get(jsonPath);
        if (Files.exists(path)) {
            try {
                json = Files.readString(path, StandardCharsets.UTF_8);
            } catch (IOException e) {
                throw new RuntimeException("Failed to read ground truth from " + jsonPath, e);
            }
        } else {
            // Try as classpath resource
            try (InputStream is = GroundTruthData.class.getResourceAsStream(jsonPath)) {
                if (is == null) {
                    throw new IllegalArgumentException("Ground truth not found: " + jsonPath);
                }
                json = readAll(is);
            } catch (IOException e) {
                throw new RuntimeException("Failed to read ground truth resource " + jsonPath, e);
            }
        }

        List<Map<String, Object>> rawList = (List<Map<String, Object>>) Json.parse(json);
        List<Entry> entries = new ArrayList<>(rawList.size());

        for (Map<String, Object> map : rawList) {
            String chunkHash = (String) map.get("chunk_hash");

            if (map.containsKey("error")) {
                entries.add(new Entry(chunkHash, null, null, -1, (String) map.get("error")));
                continue;
            }

            @SuppressWarnings("unchecked")
            List<Number> tokenList = (List<Number>) map.get("tokens");
            int[] tokens = new int[tokenList.size()];
            for (int i = 0; i < tokenList.size(); i++) {
                tokens[i] = tokenList.get(i).intValue();
            }

            String decoded = (String) map.get("decoded");
            int tokenCount = ((Number) map.get("token_count")).intValue();

            entries.add(new Entry(chunkHash, tokens, decoded, tokenCount, null));
        }

        return new GroundTruthData(name, entries);
    }

    private static String readAll(InputStream is) throws IOException {
        StringBuilder sb = new StringBuilder();
        char[] buffer = new char[8192];
        try (InputStreamReader reader = new InputStreamReader(is, StandardCharsets.UTF_8)) {
            int read;
            while ((read = reader.read(buffer)) != -1) {
                sb.append(buffer, 0, read);
            }
        }
        return sb.toString();
    }

    public static final class Entry {
        private final String chunkHash;
        private final int[] tokens;
        private final String decoded;
        private final int tokenCount;
        private final String error;

        public Entry(String chunkHash, int[] tokens, String decoded, int tokenCount, String error) {
            this.chunkHash = chunkHash;
            this.tokens = tokens;
            this.decoded = decoded;
            this.tokenCount = tokenCount;
            this.error = error;
        }

        public String chunkHash() {
            return chunkHash;
        }

        public int[] tokens() {
            return tokens;
        }

        public String decoded() {
            return decoded;
        }

        public int tokenCount() {
            return tokenCount;
        }

        public String error() {
            return error;
        }

        public boolean hasError() {
            return error != null;
        }
    }
}
