<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.qxotic</groupId>
    <artifactId>jinfer-parent</artifactId>
    <version>0.1.0</version>
  </parent>

  <artifactId>jinfer-xmaple</artifactId>
  <packaging>jar</packaging>
  <name>jinfer-xmaple</name>
  <description>MemoryView inference for Maple.</description>

  <dependencies>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>jota-memory</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>jinfer-xcore</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>jinfer-xkernels</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>jinfer-xboundary</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>jinfer-xchat</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>gguf</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>toknroll-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>toknroll-gguf</artifactId>
    </dependency>
    <dependency>
      <groupId>com.qxotic</groupId>
      <artifactId>jinfer-testkit</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <classpathDependencyExcludes>
            <classpathDependencyExclude>com.qxotic:jam-native</classpathDependencyExclude>
            <classpathDependencyExclude>com.qxotic:jam-vector</classpathDependencyExclude>
            <classpathDependencyExclude>com.qxotic:jam-scalar</classpathDependencyExclude>
          </classpathDependencyExcludes>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
