package com.qxotic.jam.vector;

import static com.qxotic.jam.vector.VectorSupport.F_SPECIES;
import static com.qxotic.jam.vector.VectorSupport.putFloat;
import static com.qxotic.jam.vector.VectorSupport.readFloat16;
import static com.qxotic.jam.vector.VectorSupport.vectorBase;
import static com.qxotic.jam.vector.VectorSupport.vectorSegment;

import com.qxotic.jam.JAM;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.nio.ByteOrder;
import java.util.HashMap;
import java.util.Map;
import jdk.incubator.vector.ByteVector;
import jdk.incubator.vector.FloatVector;
import jdk.incubator.vector.VectorOperators;
import jdk.incubator.vector.VectorSpecies;

// GENERATED by gen_q8lab.py - do not edit by hand. Q8_0 tile bake-off lab.
final class Q8Lab {
    private static final int BLOCK = 32, TYPE = 34;
    private static final VectorSpecies<Byte> B128 = ByteVector.SPECIES_128;
    private static int STREAM_HALVES = 2; // non-final: blocks unroll, keeps live set minimal
    static final Map<String, int[]> RC = new HashMap<>();

    static {
        RC.put("32mul", new int[] {3, 2});
        RC.put("32fma", new int[] {3, 2});
        RC.put("32ptr", new int[] {3, 2});
        RC.put("24mul", new int[] {2, 4});
        RC.put("24fma", new int[] {2, 4});
        RC.put("42mul", new int[] {4, 2});
        RC.put("42fma", new int[] {4, 2});
        RC.put("33fma", new int[] {3, 3});
        RC.put("34s", new int[] {3, 4});
        RC.put("26s", new int[] {2, 6});
        RC.put("44s", new int[] {4, 4});
        RC.put("62s", new int[] {6, 2});
        RC.put("63s", new int[] {6, 3});
        RC.put("45s", new int[] {4, 5});
        RC.put("54s", new int[] {5, 4});
        RC.put("22fma", new int[] {2, 2});
    }

    static final String[] NAMES =
            "32mul,32fma,32ptr,24mul,24fma,42mul,42fma,33fma,34s,26s,44s,62s,63s,45s,54s,22fma"
                    .split(",");

    public static void main(String[] args) {
        String filter = args.length > 0 ? args[0] : "";
        Arena arena = Arena.ofShared();
        java.util.Random rng = new java.util.Random(3);

        QuantWeights.Weight cw = QuantWeights.encode(JAM.Q8_0, 105, 256, arena, rng);
        float[] cact = QuantWeights.gaussians(13 * 256, rng);

        int m = args.length > 1 ? Integer.parseInt(args[1]) : 4080;
        int k = args.length > 2 ? Integer.parseInt(args[2]) : 4096;
        int n = args.length > 3 ? Integer.parseInt(args[3]) : 512;
        QuantWeights.Weight pw = QuantWeights.encode(JAM.Q8_0, m, k, arena, rng);
        MemorySegment a = arena.allocate((long) n * k * 4, 64);
        float[] av = QuantWeights.gaussians(n * k, rng);
        for (int i = 0; i < av.length; i++)
            a.set(java.lang.foreign.ValueLayout.JAVA_FLOAT_UNALIGNED, i * 4L, av[i]);
        MemorySegment o = arena.allocate((long) n * m * 4, 64);
        MemorySegment ca = arena.allocate((long) 13 * 256 * 4, 64);
        for (int i = 0; i < cact.length; i++)
            ca.set(java.lang.foreign.ValueLayout.JAVA_FLOAT_UNALIGNED, i * 4L, cact[i]);
        MemorySegment co = arena.allocate((long) 13 * 105 * 4, 64);

        MemorySegment g = VectorSupport.GLOBAL;
        double flops = 2.0 * m * n * k;
        for (String name : NAMES) {
            if (!filter.isEmpty() && !name.contains(filter)) continue;
            int[] rc = RC.get(name);
            gemmLab(name, cw.seg(), g, ca.address(), co.address(), 256, 105, 13, 105, 256);
            boolean ok = true;
            for (int j = 0; j < 13 && ok; j++)
                for (int i = 0; i < 105 && ok; i++) {
                    double[] ref = QuantWeights.refDot(cw, cact, i, j, 256);
                    float vv =
                            co.get(
                                    java.lang.foreign.ValueLayout.JAVA_FLOAT_UNALIGNED,
                                    ((long) j * 105 + i) * 4);
                    if (Math.abs(vv - ref[0]) > ref[1] * 1e-2 + 1e-3) {
                        System.out.printf(
                                "%-6s INCORRECT [%d,%d]: %f vs %f%n", name, i, j, vv, ref[0]);
                        ok = false;
                    }
                }
            if (!ok) continue;
            for (int i = 0; i < 3; i++)
                gemmLab(name, pw.seg(), g, a.address(), o.address(), k, m, n, m, k);
            double best = Double.MAX_VALUE;
            for (int i = 0; i < 6; i++) {
                long t0 = System.nanoTime();
                gemmLab(name, pw.seg(), g, a.address(), o.address(), k, m, n, m, k);
                best = Math.min(best, (System.nanoTime() - t0) / 1e9);
            }
            System.out.printf("%-6s %8.1f GF/s%n", name, flops / best / 1e9);
        }
    }

    static void gemmLab(
            String name,
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int n,
            int m,
            int k) {
        int R = RC.get(name)[0], C = RC.get(name)[1];
        for (int row = 0; row < m; row += R) {
            if (row + R > m) {
                for (int r = row; r < m; r++)
                    for (int s = 0; s < n; s++)
                        edu(w, x, xBase, outAddr, thatStride, outStride, k, r, s);
                break;
            }
            int s = 0;
            for (; s + C <= n; s += C)
                tile(name, w, x, xBase, outAddr, thatStride, outStride, k, row, s);
            for (; s < n; s++)
                for (int r = 0; r < R; r++)
                    edu(w, x, xBase, outAddr, thatStride, outStride, k, row + r, s);
        }
    }

    static void tile(
            String name,
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        switch (name) {
            case "32mul" -> t_32mul(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "32fma" -> t_32fma(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "32ptr" -> t_32ptr(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "24mul" -> t_24mul(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "24fma" -> t_24fma(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "42mul" -> t_42mul(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "42fma" -> t_42fma(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "33fma" -> t_33fma(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "34s" -> t_34s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "26s" -> t_26s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "44s" -> t_44s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "62s" -> t_62s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "63s" -> t_63s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "45s" -> t_45s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "54s" -> t_54s(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            case "22fma" -> t_22fma(w, x, xBase, outAddr, thatStride, outStride, dim1, row, s);
            default -> throw new IllegalArgumentException(name);
        }
    }

    static FloatVector dec(MemorySegment ws, long off, float d) {
        return ((FloatVector)
                        ByteVector.fromMemorySegment(B128, ws, off, ByteOrder.LITTLE_ENDIAN)
                                .castShape(F_SPECIES, 0))
                .mul(d);
    }

    static FloatVector ld(MemorySegment x, long off) {
        return FloatVector.fromMemorySegment(F_SPECIES, x, off, ByteOrder.LITTLE_ENDIAN);
    }

    static float red(FloatVector v) {
        return v.reduceLanes(VectorOperators.ADD);
    }

    static void edu(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        MemorySegment ws = vectorSegment(w);
        long wb = vectorBase(w);
        long b = (long) row * dim1 / BLOCK * TYPE;
        int x0 = s * thatStride;
        FloatVector acc = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b += TYPE) {
            float d = readFloat16(ws, wb + b);
            var w0 = dec(ws, wb + b + 2, d);
            var w1 = dec(ws, wb + b + 2 + 16, d);
            var a0 = ld(x, xBase + 4L * (x0 + j));
            var a1 = ld(x, xBase + 4L * (x0 + j + 16));
            acc = w1.fma(a1, w0.fma(a0, acc));
        }
        putFloat(outAddr + 4L * (s * outStride + row), red(acc));
    }

    static void t_32mul(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        FloatVector c00, c01, c10, c11;
        FloatVector c20, c21;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var w20 = dec(ws, wb + b2 + 2, d2);
            var w21 = dec(ws, wb + b2 + 2 + 16, d2);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = c00.add(w01.fma(a01, w00.mul(a00)));
            c10 = c10.add(w11.fma(a01, w10.mul(a00)));
            c20 = c20.add(w21.fma(a01, w20.mul(a00)));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = c01.add(w01.fma(a11, w00.mul(a10)));
            c11 = c11.add(w11.fma(a11, w10.mul(a10)));
            c21 = c21.add(w21.fma(a11, w20.mul(a10)));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
    }

    static void t_32fma(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        FloatVector c00, c01, c10, c11;
        FloatVector c20, c21;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var w20 = dec(ws, wb + b2 + 2, d2);
            var w21 = dec(ws, wb + b2 + 2 + 16, d2);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = w01.fma(a01, w00.fma(a00, c00));
            c10 = w11.fma(a01, w10.fma(a00, c10));
            c20 = w21.fma(a01, w20.fma(a00, c20));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = w01.fma(a11, w00.fma(a10, c01));
            c11 = w11.fma(a11, w10.fma(a10, c11));
            c21 = w21.fma(a11, w20.fma(a10, c21));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
    }

    static void t_32ptr(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long a0 = xBase + 4L * (s * thatStride);
        long a1 = a0 + 4L * thatStride;
        FloatVector c00, c01, c10, c11;
        FloatVector c20, c21;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        for (int j = 0;
                j < dim1;
                j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, a0 += 128, a1 += 128) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var w20 = dec(ws, wb + b2 + 2, d2);
            var w21 = dec(ws, wb + b2 + 2 + 16, d2);
            var a00 = ld(x, a0);
            var a01 = ld(x, a0 + 64);
            c00 = c00.add(w01.fma(a01, w00.mul(a00)));
            c10 = c10.add(w11.fma(a01, w10.mul(a00)));
            c20 = c20.add(w21.fma(a01, w20.mul(a00)));
            var a10 = ld(x, a1);
            var a11 = ld(x, a1 + 64);
            c01 = c01.add(w01.fma(a11, w00.mul(a10)));
            c11 = c11.add(w11.fma(a11, w10.mul(a10)));
            c21 = c21.add(w21.fma(a11, w20.mul(a10)));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
    }

    static void t_24mul(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c10, c11, c12, c13;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = c00.add(w01.fma(a01, w00.mul(a00)));
            c10 = c10.add(w11.fma(a01, w10.mul(a00)));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = c01.add(w01.fma(a11, w00.mul(a10)));
            c11 = c11.add(w11.fma(a11, w10.mul(a10)));
            var a20 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j));
            var a21 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + 16));
            c02 = c02.add(w01.fma(a21, w00.mul(a20)));
            c12 = c12.add(w11.fma(a21, w10.mul(a20)));
            var a30 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j));
            var a31 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + 16));
            c03 = c03.add(w01.fma(a31, w00.mul(a30)));
            c13 = c13.add(w11.fma(a31, w10.mul(a30)));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
    }

    static void t_24fma(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c10, c11, c12, c13;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = w01.fma(a01, w00.fma(a00, c00));
            c10 = w11.fma(a01, w10.fma(a00, c10));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = w01.fma(a11, w00.fma(a10, c01));
            c11 = w11.fma(a11, w10.fma(a10, c11));
            var a20 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j));
            var a21 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + 16));
            c02 = w01.fma(a21, w00.fma(a20, c02));
            c12 = w11.fma(a21, w10.fma(a20, c12));
            var a30 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j));
            var a31 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + 16));
            c03 = w01.fma(a31, w00.fma(a30, c03));
            c13 = w11.fma(a31, w10.fma(a30, c13));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
    }

    static void t_42mul(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        FloatVector c00, c01, c10, c11;
        FloatVector c20, c21, c30, c31;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var w20 = dec(ws, wb + b2 + 2, d2);
            var w21 = dec(ws, wb + b2 + 2 + 16, d2);
            var w30 = dec(ws, wb + b3 + 2, d3);
            var w31 = dec(ws, wb + b3 + 2 + 16, d3);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = c00.add(w01.fma(a01, w00.mul(a00)));
            c10 = c10.add(w11.fma(a01, w10.mul(a00)));
            c20 = c20.add(w21.fma(a01, w20.mul(a00)));
            c30 = c30.add(w31.fma(a01, w30.mul(a00)));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = c01.add(w01.fma(a11, w00.mul(a10)));
            c11 = c11.add(w11.fma(a11, w10.mul(a10)));
            c21 = c21.add(w21.fma(a11, w20.mul(a10)));
            c31 = c31.add(w31.fma(a11, w30.mul(a10)));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
    }

    static void t_42fma(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        FloatVector c00, c01, c10, c11;
        FloatVector c20, c21, c30, c31;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var w20 = dec(ws, wb + b2 + 2, d2);
            var w21 = dec(ws, wb + b2 + 2 + 16, d2);
            var w30 = dec(ws, wb + b3 + 2, d3);
            var w31 = dec(ws, wb + b3 + 2 + 16, d3);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = w01.fma(a01, w00.fma(a00, c00));
            c10 = w11.fma(a01, w10.fma(a00, c10));
            c20 = w21.fma(a01, w20.fma(a00, c20));
            c30 = w31.fma(a01, w30.fma(a00, c30));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = w01.fma(a11, w00.fma(a10, c01));
            c11 = w11.fma(a11, w10.fma(a10, c11));
            c21 = w21.fma(a11, w20.fma(a10, c21));
            c31 = w31.fma(a11, w30.fma(a10, c31));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
    }

    static void t_33fma(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        FloatVector c00, c01, c02, c10;
        FloatVector c11, c12, c20, c21;
        FloatVector c22;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c22 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var w20 = dec(ws, wb + b2 + 2, d2);
            var w21 = dec(ws, wb + b2 + 2 + 16, d2);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = w01.fma(a01, w00.fma(a00, c00));
            c10 = w11.fma(a01, w10.fma(a00, c10));
            c20 = w21.fma(a01, w20.fma(a00, c20));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = w01.fma(a11, w00.fma(a10, c01));
            c11 = w11.fma(a11, w10.fma(a10, c11));
            c21 = w21.fma(a11, w20.fma(a10, c21));
            var a20 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j));
            var a21 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + 16));
            c02 = w01.fma(a21, w00.fma(a20, c02));
            c12 = w11.fma(a21, w10.fma(a20, c12));
            c22 = w21.fma(a21, w20.fma(a20, c22));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 2), red(c22));
    }

    static void t_34s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c10, c11, c12, c13;
        FloatVector c20, c21, c22, c23;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c22 = FloatVector.zero(F_SPECIES);
        c23 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var w2 = dec(ws, wb + b2 + 2 + h * 16, d2);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                var a2 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + h * 16));
                var a3 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c02 = w0.fma(a2, c02);
                c03 = w0.fma(a3, c03);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c12 = w1.fma(a2, c12);
                c13 = w1.fma(a3, c13);
                c20 = w2.fma(a0, c20);
                c21 = w2.fma(a1, c21);
                c22 = w2.fma(a2, c22);
                c23 = w2.fma(a3, c23);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 2), red(c22));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 2), red(c23));
    }

    static void t_26s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c04, c05, c10, c11;
        FloatVector c12, c13, c14, c15;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c04 = FloatVector.zero(F_SPECIES);
        c05 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        c14 = FloatVector.zero(F_SPECIES);
        c15 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                var a2 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + h * 16));
                var a3 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + h * 16));
                var a4 = ld(x, xBase + 4L * (((s + 4) * thatStride) + j + h * 16));
                var a5 = ld(x, xBase + 4L * (((s + 5) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c02 = w0.fma(a2, c02);
                c03 = w0.fma(a3, c03);
                c04 = w0.fma(a4, c04);
                c05 = w0.fma(a5, c05);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c12 = w1.fma(a2, c12);
                c13 = w1.fma(a3, c13);
                c14 = w1.fma(a4, c14);
                c15 = w1.fma(a5, c15);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
        putFloat(outAddr + 4L * ((s + 4) * outStride + row + 0), red(c04));
        putFloat(outAddr + 4L * ((s + 4) * outStride + row + 1), red(c14));
        putFloat(outAddr + 4L * ((s + 5) * outStride + row + 0), red(c05));
        putFloat(outAddr + 4L * ((s + 5) * outStride + row + 1), red(c15));
    }

    static void t_44s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c10, c11, c12, c13;
        FloatVector c20, c21, c22, c23;
        FloatVector c30, c31, c32, c33;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c22 = FloatVector.zero(F_SPECIES);
        c23 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        c32 = FloatVector.zero(F_SPECIES);
        c33 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var w2 = dec(ws, wb + b2 + 2 + h * 16, d2);
                var w3 = dec(ws, wb + b3 + 2 + h * 16, d3);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                var a2 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + h * 16));
                var a3 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c02 = w0.fma(a2, c02);
                c03 = w0.fma(a3, c03);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c12 = w1.fma(a2, c12);
                c13 = w1.fma(a3, c13);
                c20 = w2.fma(a0, c20);
                c21 = w2.fma(a1, c21);
                c22 = w2.fma(a2, c22);
                c23 = w2.fma(a3, c23);
                c30 = w3.fma(a0, c30);
                c31 = w3.fma(a1, c31);
                c32 = w3.fma(a2, c32);
                c33 = w3.fma(a3, c33);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 2), red(c22));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 3), red(c32));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 2), red(c23));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 3), red(c33));
    }

    static void t_62s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        long b4 = b3 + rowStride;
        long b5 = b4 + rowStride;
        FloatVector c00, c01, c10, c11;
        FloatVector c20, c21, c30, c31;
        FloatVector c40, c41, c50, c51;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        c40 = FloatVector.zero(F_SPECIES);
        c41 = FloatVector.zero(F_SPECIES);
        c50 = FloatVector.zero(F_SPECIES);
        c51 = FloatVector.zero(F_SPECIES);
        for (int j = 0;
                j < dim1;
                j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE, b4 += TYPE,
                        b5 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            float d4 = readFloat16(ws, wb + b4);
            float d5 = readFloat16(ws, wb + b5);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var w2 = dec(ws, wb + b2 + 2 + h * 16, d2);
                var w3 = dec(ws, wb + b3 + 2 + h * 16, d3);
                var w4 = dec(ws, wb + b4 + 2 + h * 16, d4);
                var w5 = dec(ws, wb + b5 + 2 + h * 16, d5);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c20 = w2.fma(a0, c20);
                c21 = w2.fma(a1, c21);
                c30 = w3.fma(a0, c30);
                c31 = w3.fma(a1, c31);
                c40 = w4.fma(a0, c40);
                c41 = w4.fma(a1, c41);
                c50 = w5.fma(a0, c50);
                c51 = w5.fma(a1, c51);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 4), red(c40));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 5), red(c50));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 4), red(c41));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 5), red(c51));
    }

    static void t_63s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        long b4 = b3 + rowStride;
        long b5 = b4 + rowStride;
        FloatVector c00, c01, c02, c10;
        FloatVector c11, c12, c20, c21;
        FloatVector c22, c30, c31, c32;
        FloatVector c40, c41, c42, c50;
        FloatVector c51, c52;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c22 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        c32 = FloatVector.zero(F_SPECIES);
        c40 = FloatVector.zero(F_SPECIES);
        c41 = FloatVector.zero(F_SPECIES);
        c42 = FloatVector.zero(F_SPECIES);
        c50 = FloatVector.zero(F_SPECIES);
        c51 = FloatVector.zero(F_SPECIES);
        c52 = FloatVector.zero(F_SPECIES);
        for (int j = 0;
                j < dim1;
                j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE, b4 += TYPE,
                        b5 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            float d4 = readFloat16(ws, wb + b4);
            float d5 = readFloat16(ws, wb + b5);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var w2 = dec(ws, wb + b2 + 2 + h * 16, d2);
                var w3 = dec(ws, wb + b3 + 2 + h * 16, d3);
                var w4 = dec(ws, wb + b4 + 2 + h * 16, d4);
                var w5 = dec(ws, wb + b5 + 2 + h * 16, d5);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                var a2 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c02 = w0.fma(a2, c02);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c12 = w1.fma(a2, c12);
                c20 = w2.fma(a0, c20);
                c21 = w2.fma(a1, c21);
                c22 = w2.fma(a2, c22);
                c30 = w3.fma(a0, c30);
                c31 = w3.fma(a1, c31);
                c32 = w3.fma(a2, c32);
                c40 = w4.fma(a0, c40);
                c41 = w4.fma(a1, c41);
                c42 = w4.fma(a2, c42);
                c50 = w5.fma(a0, c50);
                c51 = w5.fma(a1, c51);
                c52 = w5.fma(a2, c52);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 4), red(c40));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 5), red(c50));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 4), red(c41));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 5), red(c51));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 2), red(c22));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 3), red(c32));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 4), red(c42));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 5), red(c52));
    }

    static void t_45s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c04, c10, c11, c12;
        FloatVector c13, c14, c20, c21;
        FloatVector c22, c23, c24, c30;
        FloatVector c31, c32, c33, c34;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c04 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        c14 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c22 = FloatVector.zero(F_SPECIES);
        c23 = FloatVector.zero(F_SPECIES);
        c24 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        c32 = FloatVector.zero(F_SPECIES);
        c33 = FloatVector.zero(F_SPECIES);
        c34 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var w2 = dec(ws, wb + b2 + 2 + h * 16, d2);
                var w3 = dec(ws, wb + b3 + 2 + h * 16, d3);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                var a2 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + h * 16));
                var a3 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + h * 16));
                var a4 = ld(x, xBase + 4L * (((s + 4) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c02 = w0.fma(a2, c02);
                c03 = w0.fma(a3, c03);
                c04 = w0.fma(a4, c04);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c12 = w1.fma(a2, c12);
                c13 = w1.fma(a3, c13);
                c14 = w1.fma(a4, c14);
                c20 = w2.fma(a0, c20);
                c21 = w2.fma(a1, c21);
                c22 = w2.fma(a2, c22);
                c23 = w2.fma(a3, c23);
                c24 = w2.fma(a4, c24);
                c30 = w3.fma(a0, c30);
                c31 = w3.fma(a1, c31);
                c32 = w3.fma(a2, c32);
                c33 = w3.fma(a3, c33);
                c34 = w3.fma(a4, c34);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 2), red(c22));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 3), red(c32));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 2), red(c23));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 3), red(c33));
        putFloat(outAddr + 4L * ((s + 4) * outStride + row + 0), red(c04));
        putFloat(outAddr + 4L * ((s + 4) * outStride + row + 1), red(c14));
        putFloat(outAddr + 4L * ((s + 4) * outStride + row + 2), red(c24));
        putFloat(outAddr + 4L * ((s + 4) * outStride + row + 3), red(c34));
    }

    static void t_54s(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        long b2 = b1 + rowStride;
        long b3 = b2 + rowStride;
        long b4 = b3 + rowStride;
        FloatVector c00, c01, c02, c03;
        FloatVector c10, c11, c12, c13;
        FloatVector c20, c21, c22, c23;
        FloatVector c30, c31, c32, c33;
        FloatVector c40, c41, c42, c43;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c02 = FloatVector.zero(F_SPECIES);
        c03 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        c12 = FloatVector.zero(F_SPECIES);
        c13 = FloatVector.zero(F_SPECIES);
        c20 = FloatVector.zero(F_SPECIES);
        c21 = FloatVector.zero(F_SPECIES);
        c22 = FloatVector.zero(F_SPECIES);
        c23 = FloatVector.zero(F_SPECIES);
        c30 = FloatVector.zero(F_SPECIES);
        c31 = FloatVector.zero(F_SPECIES);
        c32 = FloatVector.zero(F_SPECIES);
        c33 = FloatVector.zero(F_SPECIES);
        c40 = FloatVector.zero(F_SPECIES);
        c41 = FloatVector.zero(F_SPECIES);
        c42 = FloatVector.zero(F_SPECIES);
        c43 = FloatVector.zero(F_SPECIES);
        for (int j = 0;
                j < dim1;
                j += BLOCK, b0 += TYPE, b1 += TYPE, b2 += TYPE, b3 += TYPE, b4 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            float d2 = readFloat16(ws, wb + b2);
            float d3 = readFloat16(ws, wb + b3);
            float d4 = readFloat16(ws, wb + b4);
            for (int h = 0; h < STREAM_HALVES; h++) {
                var w0 = dec(ws, wb + b0 + 2 + h * 16, d0);
                var w1 = dec(ws, wb + b1 + 2 + h * 16, d1);
                var w2 = dec(ws, wb + b2 + 2 + h * 16, d2);
                var w3 = dec(ws, wb + b3 + 2 + h * 16, d3);
                var w4 = dec(ws, wb + b4 + 2 + h * 16, d4);
                var a0 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + h * 16));
                var a1 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + h * 16));
                var a2 = ld(x, xBase + 4L * (((s + 2) * thatStride) + j + h * 16));
                var a3 = ld(x, xBase + 4L * (((s + 3) * thatStride) + j + h * 16));
                c00 = w0.fma(a0, c00);
                c01 = w0.fma(a1, c01);
                c02 = w0.fma(a2, c02);
                c03 = w0.fma(a3, c03);
                c10 = w1.fma(a0, c10);
                c11 = w1.fma(a1, c11);
                c12 = w1.fma(a2, c12);
                c13 = w1.fma(a3, c13);
                c20 = w2.fma(a0, c20);
                c21 = w2.fma(a1, c21);
                c22 = w2.fma(a2, c22);
                c23 = w2.fma(a3, c23);
                c30 = w3.fma(a0, c30);
                c31 = w3.fma(a1, c31);
                c32 = w3.fma(a2, c32);
                c33 = w3.fma(a3, c33);
                c40 = w4.fma(a0, c40);
                c41 = w4.fma(a1, c41);
                c42 = w4.fma(a2, c42);
                c43 = w4.fma(a3, c43);
            }
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 2), red(c20));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 3), red(c30));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 4), red(c40));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 2), red(c21));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 3), red(c31));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 4), red(c41));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 0), red(c02));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 1), red(c12));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 2), red(c22));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 3), red(c32));
        putFloat(outAddr + 4L * ((s + 2) * outStride + row + 4), red(c42));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 0), red(c03));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 1), red(c13));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 2), red(c23));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 3), red(c33));
        putFloat(outAddr + 4L * ((s + 3) * outStride + row + 4), red(c43));
    }

    static void t_22fma(
            MemorySegment w,
            MemorySegment x,
            long xBase,
            long outAddr,
            int thatStride,
            int outStride,
            int dim1,
            int row,
            int s) {
        final MemorySegment ws = vectorSegment(w);
        final long wb = vectorBase(w);
        final long rowStride = (long) dim1 / BLOCK * TYPE;
        long b0 = (long) row * dim1 / BLOCK * TYPE;
        long b1 = b0 + rowStride;
        FloatVector c00, c01, c10, c11;
        c00 = FloatVector.zero(F_SPECIES);
        c01 = FloatVector.zero(F_SPECIES);
        c10 = FloatVector.zero(F_SPECIES);
        c11 = FloatVector.zero(F_SPECIES);
        for (int j = 0; j < dim1; j += BLOCK, b0 += TYPE, b1 += TYPE) {
            float d0 = readFloat16(ws, wb + b0);
            float d1 = readFloat16(ws, wb + b1);
            var w00 = dec(ws, wb + b0 + 2, d0);
            var w01 = dec(ws, wb + b0 + 2 + 16, d0);
            var w10 = dec(ws, wb + b1 + 2, d1);
            var w11 = dec(ws, wb + b1 + 2 + 16, d1);
            var a00 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j));
            var a01 = ld(x, xBase + 4L * (((s + 0) * thatStride) + j + 16));
            c00 = w01.fma(a01, w00.fma(a00, c00));
            c10 = w11.fma(a01, w10.fma(a00, c10));
            var a10 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j));
            var a11 = ld(x, xBase + 4L * (((s + 1) * thatStride) + j + 16));
            c01 = w01.fma(a11, w00.fma(a10, c01));
            c11 = w11.fma(a11, w10.fma(a10, c11));
        }
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 0), red(c00));
        putFloat(outAddr + 4L * ((s + 0) * outStride + row + 1), red(c10));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 0), red(c01));
        putFloat(outAddr + 4L * ((s + 1) * outStride + row + 1), red(c11));
    }
}
